export const Products = [
  {
    name: "Pepsi Diet",
    energy: "350 cl",
    energyPercent: "8.6%",
    fat: "0g",
    fatPercent: "0%",
    sodium: "30mg",
    sodiumPercent: "1%",
    carbohydrates: "48g",
    carbohydratesPercent: "15.3%",
    protein: "0g",
    proteinPercent: "0%",
    quantity: "250ml",
    blueIcon: "src/assets/img/1 Pespi blue.png",
    whiteIcon: "src/assets/img/1 Pespi white.png",
    heroImg: "src/assets/img/pepsi diet.png",
  },
  {
    name: "Pepsi Classic",
    energy: "150 cl",
    energyPercent: "7.8%",
    fat: "0g",
    fatPercent: "0%",
    sodium: "30mg",
    sodiumPercent: "1%",
    carbohydrates: "41g",
    carbohydratesPercent: "14%",
    protein: "0g",
    proteinPercent: "0%",
    quantity: "330ml",
    blueIcon: "src/assets/img/2 can blue.png",
    whiteIcon: "src/assets/img/2 can white.png",
    heroImg: "src/assets/img/can.png",
  },
  {
    name: "Pepsi 500ml",
    energy: "350 cl",
    energyPercent: "12.9%",
    fat: "0g",
    fatPercent: "0%",
    sodium: "40mg",
    sodiumPercent: "2%",
    carbohydrates: "52g",
    carbohydratesPercent: "21.7%",
    protein: "0g",
    proteinPercent: "0%",
    quantity: "500ml",
    blueIcon: "src/assets/img/3 Pepsi blue.png",
    whiteIcon: "src/assets/img/3 Pepsi white.png",
    heroImg: "src/assets/img/pepsi .5ltr.png",
  },
  {
    name: "Pepsi 1ltr",
    energy: "480 cl",
    energyPercent: "10.1%",
    fat: "0g",
    fatPercent: "0%",
    sodium: "45mg",
    sodiumPercent: "2.5%",
    carbohydrates: "58g",
    carbohydratesPercent: "25.8%",
    protein: "0g",
    proteinPercent: "0%",
    quantity: "1ltr",
    blueIcon: "src/assets/img/4 Pepsi blue.png",
    whiteIcon: "src/assets/img/4 Pepsi white.png",
    heroImg: "src/assets/img/pepsi 1ltr.png",
  },
  {
    name: "Pepsi 1.5ltr",
    energy: "625 cl",
    energyPercent: "19.4%",
    fat: "0g",
    fatPercent: "0%",
    sodium: "50mg",
    sodiumPercent: "3%",
    carbohydrates: "66g",
    carbohydratesPercent: "30.9%",
    protein: "0g",
    proteinPercent: "0%",
    quantity: "1.5ltr",
    blueIcon: "src/assets/img/5 Pepsi blue.png",
    whiteIcon: "src/assets/img/5 Pepsi white.png",
    heroImg: "src/assets/img/pepsi 1.5ltr.png",
  },
  {
    name: "Pepsi 2ltr",
    energy: "729 cl",
    energyPercent: "37.2%",
    fat: "0g",
    fatPercent: "0%",
    sodium: "560mg",
    sodiumPercent: "4%",
    carbohydrates: "69g",
    carbohydratesPercent: "33.2%",
    protein: "0g",
    proteinPercent: "0%",
    quantity: "2ltr",
    blueIcon: "src/assets/img/6 Pepsi blue.png",
    whiteIcon: "src/assets/img/6 Pepsi white.png",
    heroImg: "src/assets/img/pepsi 2ltr.png",
  },
];
